### ISSUE TITLE
Clarify wage negotiation (there is no such thing for engineering)

### ISSUE THREAD

**Issue by smacker** [src-d/guide#128]
It's better to have it here to avoid misunderstanding. Thanks!

**Comment by eiso** [comment]
@smacker and I discussed this over Slack, we thought we should add this here.

Salaries of team members have never been in the guide because unfortunately it's illegal in Spain to make them public. In engineering we've always had salary levels, and we still do. Those each come with a specific salary, we don't have individually negotiated contracts. The only exception to this is roles of which we have only one person, like, office manager.

**Comment by eiso** [comment]
@tsolakoua now this is clarified, can you please make sure this becomes part of the talent documentation in the guide.
