### ISSUE TITLE
Virtual Office Room

### ISSUE THREAD

**Issue by jorgeschnura** [src-d/guide#133]
One of the main issues that happen with remote teams is that you lose the "serendipity" of conversations starting and ending up in something new and useful.

I'd like to open up this discussion with a proposal in order to avoid this issue:

I'd like to set up a screen in the kitchen with a webcam where a Zoom Room is constantly open and you can see the people who are working remotely. These people would decide if they are muted and/or deafened. The idea is that you can start a casual conversation with any of them or that they can join a kitchen conversation as if they were in the office.
It would also be possible for people who are remote and have joined that same Zoom Room to start a conversation with each other as if they would be sharing a physical room.

Potential issues: The kitchen will become less private as anyone in remote and logged into that room can undeafen theirself and start listening to any conversation happening.

Everyone working remotely would be encourage to join this Zoom Room if they want to in order to be better integrated with the rest of our team members.

This idea can be executed with or without the kitchen solution.

**Comment by dpordomingo** [comment]
I like pretty much the idea and the reasoning in behind. I think it could be difficult to implement, and remote people might want to avoid joining this room. But from an in premise worker pov, I like a lot this idea.
About the implementation, once of the most importan things would be the speakers and mics; if they're the usual ones, the quality of the conversation can be to low.

**Comment by eiso** [comment]
Great idea! I like it for the reason you mentioned but also because it allows us to be present at the welcome breakfasts that happen in the Madrid office. I would, however, have it so that people join when they feel like chatting, including people in the kitchen. Otherwise, it is hard to know who you can speak too when. What I mean by this is a variation on your idea where:

Person A in the kitchen sees Person B joining the kitchen room and decides to unmute the kitchen from the Logitech speaker and have a conversation/join in an existing conversation.

Person B who is remote, and person C who is remote both join the room and have a nice conversation, person A in the kitchen chooses to turn on the sound/unmute and joins in. 

This way you avoid part of the privacy issue with the kitchen and you also make it a virtual meeting place amongst people who are remote. And people can still choose to be there on video constantly but I  imagine, it feels weird knowing that your face is close up on a screen without you seeing yourself on it. So this would offer both options. 

I agree with @dpordomingo's point that we'd need much better sound tech then we have today for this but I am sure that can be solved.

This idea would also work nicely with the remote camera control that people can now use.

**Comment by marnovo** [comment]
Definitely into "the Water Cooler Channel" and I like Eiso's solution.

Actually I wouldn't mind to go one step further and keep mics always on, as IRL there's not really a "mute".

There will always be a privacy trade-off, but in a way we are all in an office that's a public place, and we deem to be transparent. If something is really private it should be treated at closed doors.

**Comment by eiso** [comment]
@marnovo mic always on in the kitchen I wouldn't do because I've often seen people use the kitchen for phone calls, private conversations discussing the weekend etc. and an always-on mic feels way too big brother/black mirror for me. The transparency we have as a company shouldn't interfere with personal matters in which people should be as private as they want to be.

**Comment by gomesfernanda** [comment]
I myself being an on-premise employee like very much the idea.

I agree that the mic should have the option to be on or off, because if a person is in the kitchen talking to another about a private subject, there's a huge difference between a 3rd person coming into the kitchen and a "virtual" person entering the room without the 2 people in the kitchen noticing.

It's not about company's transparency, but about people sharing personal matters and the choice they make with whom to share it. If people don't feel "safe" talking about personal matters in the kitchen, they will hesitate to bond with each other (and will tend to have 'small talk'), which I believe would be the opposite of this initiative's goal.

**Comment by jorgeschnura** [comment]
Why not just have it be on by default and if someone is going to talk about something private or sensitive that person can turn it off and turn it on again once the conversation has finished?

I also wouldn't restrain people from joining the room if they want to. Eiso mentioned that only people looking for a chat should join, but I think it is OK to allow anyone to join. If you don't want to be chatted up because you need concentration the you can leave for that time

**Comment by eiso** [comment]
> Eiso mentioned that only people looking for a chat should join, but I think it is OK to allow anyone to join. I

I actually agree ;)

> And people can still choose to be there on video constantly

**Comment by eiso** [comment]
@jorgeschnura what we could do before we have the hardware setup is have an appear.in room that people can already join in the same manner, "virtual hangout" that will soon be available in the kitchen. Appear.in rooms support up to 14 members and since they are in the browser, easy to use.

**Comment by jorgeschnura** [comment]
Sure, let's use https://appear.in/source{d} for now.
I'll create the guide documentation with this solution and will update once we have the hardware set up

**Comment by eiso** [comment]
@jorgeschnura if you remove that room from your account, I can make it a full feature room under my paid one.

**Comment by jorgeschnura** [comment]
Ah OK, didn't know you got a paid one already

**Comment by jorgeschnura** [comment]
Done

**Comment by eiso** [comment]
I did, it's what powers all of the remote accounts: https://github.com/src-d/company/blob/master/communication/video-conferencing.md#claimed-rooms-for-those-who-are-fullyfrequently-remote

**Comment by jorgeschnura** [comment]
https://appear.in/source{d} it's working since a few days, with little success though so far

**Comment by eiso** [comment]
I am joining now, will try it for a few days to see if anyone joins me.

**Comment by eiso** [comment]
After 40 mins, I needed to stop it, it was taking 100% of one core of my CPU, GPU to the max and creeping up ram. It was a lot better still than using Zoom but not possible to do from my main laptop. This reminds me of a company I visited a few years back that were using cheap tablets to have the virtual room on everyone's desk.

**Comment by jorgeschnura** [comment]
Hmmm, that makes it quite unusable, yes.
Will have a look at tablets. I remember we did the same for Curro. How did it work @mcuadros ?

**Comment by mcuadros** [comment]
Terrible bad

**Comment by jorgeschnura** [comment]
We will leave this for now as there are technical problems that are hard to solve
