### ISSUE TITLE
New Member Asynchronous Presentation

### ISSUE THREAD

**Issue by jorgeschnura** [src-d/guide#136]
According to research, one of the down-sides of working remotely is that is becomes harder to establish a personal relationship with other team members.

For this reason, I would create either a Github repo or a Slack channel (or both), where everyone has to post an introduction of themselves. This introduction (precise content to be defined) should have personal questions, as well as a link to those social media accounts (Instagram, Twitter, Medium, FB, etc.) the new sourcerer is comfortable with sharing, so that we can establish more personal relationships outside of work activities.

Ideally it should be a Github Issue per member, where we can use the comments to ask questions to the new member. Once the issue is posted it should be published on a "new_sourcerers" Slack channel so that people get notified.

**Comment by campoy** [comment]
I feel like this could also be a great start for the "Why I joined source{d}" blog post series.
Basically same kind of information, just less private stuff since I don't want people to be harassed online 😄

**Comment by eiso** [comment]
I like this idea and +1 on @campoy's suggestion as using this as a kick off for the blog post. What kind of questions/content do you have in mind? Also know that this can be scheduled with Geekbot.io.

**Comment by jorgeschnura** [comment]
I had thought of the following:
- What's your name?
- How old are you?
- Where are you from?
- Where have you lived?
- What languages do you speak?
- What are you going to be doing at source{d}?
- Would like to share your Twitter, Instagram or Medium?
- What are your main hobbies?

The rest should be a Q&A from the team. If we see some questions being repeated often we can add them as standard.

What do you think?

**Comment by eiso** [comment]
I like them! Instagram makes me cringe though ;) but that might just be me. 

I like the idea of the rest just being a simple QnA in the channel. 

Geekbot is not really made for it but we could setup a custom report that asks someone once and then is without participants after:

![2018-02-23-123655_1873x1591_scrot](https://user-images.githubusercontent.com/1247608/36594517-4afafc34-1896-11e8-88ba-8fc00652726c.png)

**Comment by dennwc** [comment]
I know that there are people that were in source{d} for ages, but I'd like to see these questions asked to current members and veterans as well :)

Channel might also be called `#intro`.

**Comment by dpordomingo** [comment]
I agree with Denys, people already in src should also share this info, so new mates would also know us better.

About questionnaire, I'd consider these two from our eng QA interview:

> What programming languages do you know?

It might be a conversation starter. Also applicable to non dev roles as Eiso programming in Haskell or Esther learning Python

> What foods do you like, do you have any allergy or you hate any food?

It might be useful for having lunch together or for Esther considering Friday lunch.

**Comment by eiso** [comment]
@dennwc you make a very good point. Maybe the format is different than or the format is the same but the summary gets stored in our private repo.

**Comment by jorgeschnura** [comment]
@eiso don't you think this would be better suited for Github than Slack? That way you can always read about your colleagues. It's harder to do on Slack

**Comment by jorgeschnura** [comment]
This has been discussed with @eiso in the Management meeting and it has been decided to keep it in Github

**Comment by estherrgarcia** [comment]
Hi!
I was thinking about this. Maybe it is because I’m so curious but I feel that I’m not going to know this person after these questions. I’m asking random things all the time in the kitchen, the typical things like, what is your favorite film, book, series,... what did you do last weekend, what are you gonna do this weekend. Thanks to that, I know no one is, like me, Atleti supporter, I know David goes climbing some Sundays to be able to join him, I know that the last film Carlos watched at the cinema was Murder at the Orient Express and I can tell him that the book is much better.  Maybe we can prepare 3 blocks of questions: serious, work & special. We don’t have to do the same questions every time. 

For example:
**1. Serious:**

- What's your name? What do your friends call you? 
- How old are you?
- Where are you from? Where have you lived?
- What languages do you speak?
- What is your favorite word in Spanish?
- Would like to share your Twitter, Instagram or Medium?

**2. Work:**
- What are you going to be doing at source{d}?
- Why did you decide to join us?
- If you could only save one programming language, which one would it be? 
- If you wanted to do an investment, what company would you choose?
- What keys on a keyboard do you not use?

**3. Special:**
- What are your main hobbies?
- What was the last lie you told?
- What was your first thought when you woke up this morning?
- What question do you hate to answer?
- What’s your favorite knock-knock joke?
- If you could have a coffee with any person in the world, who would it be?

**Comment by campoy** [comment]
I think this would be a super interesting way to create more content for the blogpost, I love the questions.

**Comment by eiso** [comment]
I really like the questions you put @estherrgarcia
