### ISSUE TITLE
Clarification of a business goals

### ISSUE THREAD

**Issue by smacker** [src-d/guide#17]
First of all, thank you for this repo. It's really helpful.
The only matter that is still unclear for me is about the product.
According to Roadmap and manifesto it looks like there is more than one.
The first one is a platform to connect developers, projects and companies through code. Is it another approach to "fix developer recruitment"?
The second one is real-time assisted programming. Do you plan to develop some tools and make them another product?
Which of them is more important? On what do you want to focus?
Do you mind to open not only how you do things, but how you sell it to potential investor?

**Comment by eiso** [comment]
@smacker I am right now working on a new post that updates on our roadmap and tackles a lot of your questions. The content will also become part of this guide. It will go live on Thursday so please bare with me a few days.

**Comment by jorgeschnura** [comment]
Thanks a lot for your comment @smacker . We're also about to release our new website which will shed more light on your questions.

We have also made our whole backlog public, which we're now cleaning up. You can find it here: https://github.com/src-d/backlog

The reason we have opened this repo up before it being complete is because we want to be completely transparent from moment one and receive feedback from the developer community as we write the guide.

**Comment by eiso** [comment]
@smacker we're still working on the post as an internal draft before it's going live. I will send you a google doc link where you can read it (and comment on it) already.
