### ISSUE TITLE
By Devs Training - Quest 1 clarification

### ISSUE THREAD

**Issue by marnovo** [src-d/guide#27]
On [Quest 1: Setup your machine on Arch Linux](https://github.com/src-d/guide/blob/master/talent/by-developers-training/README.md#quest-1-setup-your-machine-on-arch-linux) of the By Developers Training we have:
`Duration: 2 days` and `Deliverable: Fully set-up laptop`

That seems good particularly during the onboarding experience. Some however mentioned that the idea is that the person in training would have to use the set up laptop with Arch for work afterwards instead of their OS of choice.

So a few questions for clarification:
1. Is the person in training supposed to do this on their main work laptop or can it be a spare one?
2. Does the person need to use it afterwards for work for any given amount of time?
3. If that's the case above, how to deal with jobs who required different setups/OSes?

Thanks!

**Comment by jorgeschnura** [comment]
I changed to wording to say "your work laptop" to clarify on Q1 and Q2. For Q3 we only foresee this happening with the designer, for whom we will find a solution once we hire one. What I had thought of is having that person have both Mac/Windows + Arch Linux installed so that they still go through the installation process.
We will add instructions on how to keep Mac/setup Windows on them in the setup documentation.

**Comment by Serabe** [comment]
We hired a designer! Let's see what to do with this then :)

**Comment by ricardobaeta** [comment]
Tools don't make the craft, people do. Looking forward to those instructions!
